name: CreditShops
description: 'CreditShops is a plugin for Bukkit Minecraft servers that lets owners set prices of items and then sell them to players.'
main: com.domsplace.CreditShops.CreditShopsPlugin
authors: [Dominic, Jordan]
website: http://domsplace.com/
version: '1.02'
softdepend: [Vault]
commands:
   creditshops:
      description: Reload the CreditShops Configuration.
      usage: /<command> [reload]
      permission: CreditShops.creditshops
   price:
      description: Get's the price of an item by name, or the item you're holding.
      usage: /<command> (item)
      permission: CreditShops.price
   shop:
      description: Open a shop (or server shop if no shop name is entered).
      usage: /<command> [shop]
      aliases: [store, openshop, viewshop, openstore, viewstore]
      permission: CreditShops.shop
   createshop:
      description: Open a shop (or server shop if no shop name is entered).
      usage: /<command> [shop]
      aliases: [createstore, storecreate, shopcreate]
      permission: CreditShops.createshop
   shops:
      description: Gets a list of Shops
      usage: /<command>
      aliases: [listshops, stores, getshops, liststores, getstores]
      permission: CreditShops.shops
   buy:
      description: Buy items from the server at an inflated price.
      usage: /<command>
      permission: CreditShops.buy
   sell:
      description: Sell items to the server at an inflated price.
      usage: /<command>
      permission: CreditShops.sell
permissions:
   CreditShops.*:
     description: Gives access to all CreditShops permissions.
     children:
       CreditShops.creditshops: true
       CreditShops.price: true
       CreditShops.shopsign: true
       CreditShops.shop: true
       CreditShops.shops: true
       CreditShops.createshop: true
       CreditShops.override: true
       CreditShops.buy: true
       CreditShops.sell: true
       CreditShops.shopprice: true
   CreditShops.creditshops:
     description: Allows access to the creditshops command.
   CreditShops.price:
     description: Allows access to the price command.
   CreditShops.shopsign:
     description: Allows access to create Shop Signs.
   CreditShops.shop:
     description: Allows acces to the shop command.
   CreditShops.shops:
     description: Allows acces to the shops command.
   CreditShops.createshop:
     description: Allows acces to the createshop command.
   CreditShops.override:
     description: Allows acces to bypass shop sign breaking.
   CreditShops.buy:
     description: Allows acces to the buy command.
   CreditShops.sell:
     description: Allows acces to the sell command.
   CreditShops.shopprice:
     description: Allows access to set the prices of items in a player's shop.